spring:
  application:
    name: LoginApplication
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: Ov23livcqKoBixXHI6lg
            clientSecret: 3ed3e6df642441f3607fe28b078225aa2c3f3a74